### PR TITLE
Leap Motion With Unity - Basic Scene

### PR DESCRIPTION
**Pull request by yodem**

### CODE REVIEW

**Review by cynepco3hahue — COMMENTED** [review]
Please push only your code without LeapMotion unity asset module, and under README add instructions about module, that anyone will know how to install it

**Comment by abraverm** [comment]
There are number of directories that don't need version control (create .gitignore):
https://unity3d.com/learn/tutorials/topics/production/mastering-unity-project-folder-structure-version-control-systems

**Comment by abraverm** [comment]
Submitted a pull request for the Git ignore issue #5

**Comment by abraverm** [comment]
Please resubmit the pull request to https://github.com/RedHat-Israel/rosvr-leapmotion

**Pull request closed without merging**
